import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    darkMode: 'class',

    theme: {
        extend: {
            colors: {
                // CSS Variable mapping for dynamic theming (supports opacity)
                'surface-container-highest': 'rgb(var(--c-surface-container-highest) / <alpha-value>)',
                'on-surface-variant': 'rgb(var(--c-on-surface-variant) / <alpha-value>)',
                'background': 'rgb(var(--c-background) / <alpha-value>)',
                'secondary-fixed': 'rgb(var(--c-secondary-fixed) / <alpha-value>)',
                'surface-bright': 'rgb(var(--c-surface-bright) / <alpha-value>)',
                'on-primary-fixed': 'rgb(var(--c-on-primary-fixed) / <alpha-value>)',
                'secondary': 'rgb(var(--c-secondary) / <alpha-value>)',
                'on-secondary-fixed': 'rgb(var(--c-on-secondary-fixed) / <alpha-value>)',
                'on-tertiary-fixed-variant': 'rgb(var(--c-on-tertiary-fixed-variant) / <alpha-value>)',
                'outline': 'rgb(var(--c-outline) / <alpha-value>)',
                'inverse-primary': 'rgb(var(--c-inverse-primary) / <alpha-value>)',
                'tertiary-container': 'rgb(var(--c-tertiary-container) / <alpha-value>)',
                'inverse-on-surface': 'rgb(var(--c-inverse-on-surface) / <alpha-value>)',
                'primary-fixed-dim': 'rgb(var(--c-primary-fixed-dim) / <alpha-value>)',
                'on-tertiary-container': 'rgb(var(--c-on-tertiary-container) / <alpha-value>)',
                'tertiary-fixed': 'rgb(var(--c-tertiary-fixed) / <alpha-value>)',
                'on-error': 'rgb(var(--c-on-error) / <alpha-value>)',
                'surface-container-high': 'rgb(var(--c-surface-container-high) / <alpha-value>)',
                'secondary-fixed-dim': 'rgb(var(--c-secondary-fixed-dim) / <alpha-value>)',
                'on-surface': 'rgb(var(--c-on-surface) / <alpha-value>)',
                'on-primary': 'rgb(var(--c-on-primary) / <alpha-value>)',
                'surface-tint': 'rgb(var(--c-surface-tint) / <alpha-value>)',
                'primary': 'rgb(var(--c-primary) / <alpha-value>)',
                'error': 'rgb(var(--c-error) / <alpha-value>)',
                'primary-fixed': 'rgb(var(--c-primary-fixed) / <alpha-value>)',
                'surface-container-lowest': 'rgb(var(--c-surface-container-lowest) / <alpha-value>)',
                'on-tertiary': 'rgb(var(--c-on-tertiary) / <alpha-value>)',
                'surface': 'rgb(var(--c-surface) / <alpha-value>)',
                'primary-container': 'rgb(var(--c-primary-container) / <alpha-value>)',
                'on-primary-fixed-variant': 'rgb(var(--c-on-primary-fixed-variant) / <alpha-value>)',
                'on-primary-container': 'rgb(var(--c-on-primary-container) / <alpha-value>)',
                'on-secondary-container': 'rgb(var(--c-on-secondary-container) / <alpha-value>)',
                'inverse-surface': 'rgb(var(--c-inverse-surface) / <alpha-value>)',
                'surface-container-low': 'rgb(var(--c-surface-container-low) / <alpha-value>)',
                'on-tertiary-fixed': 'rgb(var(--c-on-tertiary-fixed) / <alpha-value>)',
                'tertiary': 'rgb(var(--c-tertiary) / <alpha-value>)',
                'surface-container': 'rgb(var(--c-surface-container) / <alpha-value>)',
                'on-error-container': 'rgb(var(--c-on-error-container) / <alpha-value>)',
                'on-secondary': 'rgb(var(--c-on-secondary) / <alpha-value>)',
                'error-container': 'rgb(var(--c-error-container) / <alpha-value>)',
                'surface-dim': 'rgb(var(--c-surface-dim) / <alpha-value>)',
                'tertiary-fixed-dim': 'rgb(var(--c-tertiary-fixed-dim) / <alpha-value>)',
                'outline-variant': 'rgb(var(--c-outline-variant) / <alpha-value>)',
                'on-background': 'rgb(var(--c-on-background) / <alpha-value>)',
                'surface-variant': 'rgb(var(--c-surface-variant) / <alpha-value>)',
                'on-secondary-fixed-variant': 'rgb(var(--c-on-secondary-fixed-variant) / <alpha-value>)',
                'secondary-container': 'rgb(var(--c-secondary-container) / <alpha-value>)',
                
                // Nav / Layout specific
                'nav-bg': 'rgb(var(--c-nav-bg) / <alpha-value>)',
                'nav-border': 'rgb(var(--c-nav-border) / <alpha-value>)',
                'nav-brand': 'rgb(var(--c-nav-brand) / <alpha-value>)',
                'nav-link': 'rgb(var(--c-nav-link) / <alpha-value>)',
                'nav-link-hover': 'rgb(var(--c-nav-link-hover) / <alpha-value>)',
                'sidebar-bg': 'rgb(var(--c-sidebar-bg) / <alpha-value>)',
                'footer-bg': 'rgb(var(--c-footer-bg) / <alpha-value>)',
                'footer-text': 'rgb(var(--c-footer-text) / <alpha-value>)',
            },
            borderRadius: {
                'DEFAULT': '0.25rem',
                'lg': '0.5rem',
                'xl': '0.75rem',
                'full': '9999px',
            },
            spacing: {
                'base': '8px',
                'sm': '12px',
                'md': '24px',
                'lg': '48px',
                'container-max': '1120px',
                'xs': '4px',
                'xl': '80px',
                'gutter': '24px',
            },
            fontFamily: {
                'sans': ['Inter', ...defaultTheme.fontFamily.sans],
                'ui-label': ['Inter'],
                'code-block': ['Space Grotesk'],
                'h1': ['Inter'],
                'h2': ['Inter'],
                'h3': ['Inter'],
                'body-lg': ['Newsreader'],
                'body-md': ['Newsreader'],
            },
            fontSize: {
                'ui-label': ['14px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
                'code-block': ['15px', { lineHeight: '1.7', letterSpacing: '0', fontWeight: '400' }],
                'h1': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
                'h2': ['30px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
                'h3': ['24px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '600' }],
                'body-lg': ['20px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
                'body-md': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
            },
        },
    },

    plugins: [forms],
};
